// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AccountType.
const (
	AccountTypeInvestor AccountType = "investor"
	AccountTypeStartup  AccountType = "startup"
	AccountTypeUser     AccountType = "user"
)

// AccountType defines model for AccountType.
type AccountType string

// CreateInvestorRequest defines model for CreateInvestorRequest.
type CreateInvestorRequest struct {
	Bio             *string `json:"bio,omitempty"`
	FocusAreas      *string `json:"focus_areas,omitempty"`
	Location        *string `json:"location,omitempty"`
	Name            string  `json:"name"`
	PortfolioSize   *int    `json:"portfolio_size,omitempty"`
	StagePreference *string `json:"stage_preference,omitempty"`
	Website         *string `json:"website,omitempty"`
}

// CreateStartupRequest defines model for CreateStartupRequest.
type CreateStartupRequest struct {
	ContactFunding *string `json:"contact_funding,omitempty"`
	ContactGeneral *string `json:"contact_general,omitempty"`
	ContactTalent  *string `json:"contact_talent,omitempty"`
	CurrentRound   *string `json:"current_round,omitempty"`
	Description    *string `json:"description,omitempty"`
	FoundedYear    *int    `json:"founded_year,omitempty"`
	FundingAsk     *string `json:"funding_ask,omitempty"`
	FundingUse     *string `json:"funding_use,omitempty"`
	Github         *string `json:"github,omitempty"`
	Industry       *string `json:"industry,omitempty"`
	Instagram      *string `json:"instagram,omitempty"`
	IsHiring       *bool   `json:"is_hiring,omitempty"`
	IsRaising      *bool   `json:"is_raising,omitempty"`
	Linkedin       *string `json:"linkedin,omitempty"`
	Location       *string `json:"location,omitempty"`
	Name           string  `json:"name"`
	OpenRoles      *string `json:"open_roles,omitempty"`
	ProductLinks   *string `json:"product_links,omitempty"`
	Stage          *string `json:"stage,omitempty"`
	Tagline        *string `json:"tagline,omitempty"`
	TeamSize       *int    `json:"team_size,omitempty"`
	TechStack      *string `json:"tech_stack,omitempty"`
	Twitter        *string `json:"twitter,omitempty"`
	Website        *string `json:"website,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Investor defines model for Investor.
type Investor struct {
	Bio           *string            `json:"bio,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`
	FocusAreas    *string            `json:"focus_areas,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	Location      *string            `json:"location,omitempty"`
	LogoUrl       *string            `json:"logo_url,omitempty"`
	Name          string             `json:"name"`
	OwnerEmail    string             `json:"owner_email"`
	OwnerId       string             `json:"owner_id"`
	PortfolioSize *int               `json:"portfolio_size,omitempty"`

	// ProfileSetup Whether the investor profile has been fully set up (defaults to false)
	ProfileSetup    *bool      `json:"profile_setup,omitempty"`
	StagePreference *string    `json:"stage_preference,omitempty"`
	UpdatedAt       *time.Time `json:"updated_at,omitempty"`
	Website         *string    `json:"website,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken The refresh token obtained from login
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	AccountType AccountType `json:"account_type"`

	// Email Required when account_type is "user"
	Email *openapi_types.Email `json:"email,omitempty"`

	// EmailPrefix Required when account_type is "startup" or "investor". The local part of the email (before @). The domain is derived from the website.
	EmailPrefix *string `json:"email_prefix,omitempty"`

	// Name Required when account_type is "startup" or "investor"
	Name *string `json:"name,omitempty"`

	// Nickname Required when account_type is "user"
	Nickname *string `json:"nickname,omitempty"`
	Password string  `json:"password"`

	// Website Required when account_type is "startup" or "investor"
	Website *string `json:"website,omitempty"`
}

// Startup defines model for Startup.
type Startup struct {
	// BannerImage URL of the banner image
	BannerImage *string `json:"banner_image,omitempty"`

	// BoostCount Total number of active boosts for this startup (boosts expire after 7 days)
	BoostCount     *int      `json:"boost_count,omitempty"`
	ContactFunding *string   `json:"contact_funding,omitempty"`
	ContactGeneral *string   `json:"contact_general,omitempty"`
	ContactTalent  *string   `json:"contact_talent,omitempty"`
	CreatedAt      time.Time `json:"created_at"`

	// CurrentRound pre-seed | seed | series-a | series-b | bridge
	CurrentRound *string `json:"current_round,omitempty"`
	Description  *string `json:"description,omitempty"`
	FoundedYear  *int    `json:"founded_year,omitempty"`
	FundingAsk   *string `json:"funding_ask,omitempty"`
	FundingUse   *string `json:"funding_use,omitempty"`
	Github       *string `json:"github,omitempty"`

	// HasBoosted Whether the current authenticated user has an active boost for this startup (only present when authenticated)
	HasBoosted *bool              `json:"has_boosted,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// Industry AI/ML | FinTech | HealthTech | Climate Tech | EdTech | SaaS | Marketplace | Developer Tools | Hardware | Consumer | Deep Tech | Logistics | Legal Tech | HR Tech | Other
	Industry  *string `json:"industry,omitempty"`
	Instagram *string `json:"instagram,omitempty"`

	// IsFavorited Whether the current authenticated user has favorited this startup (only present when authenticated)
	IsFavorited *bool   `json:"is_favorited,omitempty"`
	IsHiring    *bool   `json:"is_hiring,omitempty"`
	IsRaising   *bool   `json:"is_raising,omitempty"`
	Linkedin    *string `json:"linkedin,omitempty"`
	Location    *string `json:"location,omitempty"`
	LogoUrl     *string `json:"logo_url,omitempty"`
	Name        string  `json:"name"`

	// OpenRoles Comma-separated list of open roles
	OpenRoles  *string `json:"open_roles,omitempty"`
	OwnerEmail string  `json:"owner_email"`
	OwnerId    string  `json:"owner_id"`

	// ProductLinks JSON object with product links: {"web":"...","ios":"...","android":"..."}
	ProductLinks *string `json:"product_links,omitempty"`

	// ProfileSetup Whether the startup profile has been fully set up (defaults to false)
	ProfileSetup *bool `json:"profile_setup,omitempty"`

	// Stage idea | pre-seed | seed | series-a | series-b | growth | profitable
	Stage     *string    `json:"stage,omitempty"`
	Tagline   *string    `json:"tagline,omitempty"`
	TeamSize  *int       `json:"team_size,omitempty"`
	TechStack *string    `json:"tech_stack,omitempty"`
	Twitter   *string    `json:"twitter,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Website   *string    `json:"website,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until expiry
	ExpiresIn    int     `json:"expires_in"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	TokenType    string  `json:"token_type"`
}

// UpdateInvestorRequest defines model for UpdateInvestorRequest.
type UpdateInvestorRequest struct {
	Bio           *string `json:"bio,omitempty"`
	FocusAreas    *string `json:"focus_areas,omitempty"`
	Location      *string `json:"location,omitempty"`
	Name          *string `json:"name,omitempty"`
	PortfolioSize *int    `json:"portfolio_size,omitempty"`

	// ProfileSetup Set to true to mark the profile as complete and visible in public listings
	ProfileSetup    *bool   `json:"profile_setup,omitempty"`
	StagePreference *string `json:"stage_preference,omitempty"`
	Website         *string `json:"website,omitempty"`
}

// UpdateStartupRequest defines model for UpdateStartupRequest.
type UpdateStartupRequest struct {
	ContactFunding *string `json:"contact_funding,omitempty"`
	ContactGeneral *string `json:"contact_general,omitempty"`
	ContactTalent  *string `json:"contact_talent,omitempty"`
	CurrentRound   *string `json:"current_round,omitempty"`
	Description    *string `json:"description,omitempty"`
	FoundedYear    *int    `json:"founded_year,omitempty"`
	FundingAsk     *string `json:"funding_ask,omitempty"`
	FundingUse     *string `json:"funding_use,omitempty"`
	Github         *string `json:"github,omitempty"`
	Industry       *string `json:"industry,omitempty"`
	Instagram      *string `json:"instagram,omitempty"`
	IsHiring       *bool   `json:"is_hiring,omitempty"`
	IsRaising      *bool   `json:"is_raising,omitempty"`
	Linkedin       *string `json:"linkedin,omitempty"`
	Location       *string `json:"location,omitempty"`
	Name           *string `json:"name,omitempty"`
	OpenRoles      *string `json:"open_roles,omitempty"`
	ProductLinks   *string `json:"product_links,omitempty"`

	// ProfileSetup Set to true to mark the profile as complete and visible in public listings
	ProfileSetup *bool   `json:"profile_setup,omitempty"`
	Stage        *string `json:"stage,omitempty"`
	Tagline      *string `json:"tagline,omitempty"`
	TeamSize     *int    `json:"team_size,omitempty"`
	TechStack    *string `json:"tech_stack,omitempty"`
	Twitter      *string `json:"twitter,omitempty"`
	Website      *string `json:"website,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	AccountType AccountType        `json:"account_type"`
	CreatedAt   time.Time          `json:"created_at"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`
	KeycloakId  string             `json:"keycloak_id"`
	Nickname    string             `json:"nickname"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	Code  *string              `json:"code,omitempty"`
	Email *openapi_types.Email `json:"email,omitempty"`
}

// WebsiteCheckResponse defines model for WebsiteCheckResponse.
type WebsiteCheckResponse struct {
	Available bool `json:"available"`
}

// CheckInvestorWebsiteParams defines parameters for CheckInvestorWebsite.
type CheckInvestorWebsiteParams struct {
	Url string `form:"url" json:"url"`
}

// UploadInvestorLogoMultipartBody defines parameters for UploadInvestorLogo.
type UploadInvestorLogoMultipartBody struct {
	Logo openapi_types.File `json:"logo"`
}

// CheckStartupWebsiteParams defines parameters for CheckStartupWebsite.
type CheckStartupWebsiteParams struct {
	Url string `form:"url" json:"url"`
}

// UploadStartupBannerMultipartBody defines parameters for UploadStartupBanner.
type UploadStartupBannerMultipartBody struct {
	Banner openapi_types.File `json:"banner"`
}

// UploadStartupLogoMultipartBody defines parameters for UploadStartupLogo.
type UploadStartupLogoMultipartBody struct {
	Logo openapi_types.File `json:"logo"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// VerifyJSONRequestBody defines body for Verify for application/json ContentType.
type VerifyJSONRequestBody = VerifyRequest

// CreateInvestorJSONRequestBody defines body for CreateInvestor for application/json ContentType.
type CreateInvestorJSONRequestBody = CreateInvestorRequest

// UpdateInvestorJSONRequestBody defines body for UpdateInvestor for application/json ContentType.
type UpdateInvestorJSONRequestBody = UpdateInvestorRequest

// UploadInvestorLogoMultipartRequestBody defines body for UploadInvestorLogo for multipart/form-data ContentType.
type UploadInvestorLogoMultipartRequestBody UploadInvestorLogoMultipartBody

// CreateStartupJSONRequestBody defines body for CreateStartup for application/json ContentType.
type CreateStartupJSONRequestBody = CreateStartupRequest

// UpdateStartupJSONRequestBody defines body for UpdateStartup for application/json ContentType.
type UpdateStartupJSONRequestBody = UpdateStartupRequest

// UploadStartupBannerMultipartRequestBody defines body for UploadStartupBanner for multipart/form-data ContentType.
type UploadStartupBannerMultipartRequestBody UploadStartupBannerMultipartBody

// UploadStartupLogoMultipartRequestBody defines body for UploadStartupLogo for multipart/form-data ContentType.
type UploadStartupLogoMultipartRequestBody UploadStartupLogoMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with username and password
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout (invalidate session)
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Get current authenticated user's profile
	// (GET /auth/me)
	GetMe(c *gin.Context)
	// Refresh access token using refresh token
	// (POST /auth/refresh)
	RefreshToken(c *gin.Context)
	// Begin registration for all account types — sends a verification code
	// (POST /auth/register)
	Register(c *gin.Context)
	// Verify email code and complete account creation
	// (POST /auth/verify)
	Verify(c *gin.Context)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// List all investor accounts (public)
	// (GET /investors)
	ListInvestors(c *gin.Context)
	// Create a new investor profile
	// (POST /investors)
	CreateInvestor(c *gin.Context)
	// Check whether a website URL is already registered by an investor
	// (GET /investors/check-website)
	CheckInvestorWebsite(c *gin.Context, params CheckInvestorWebsiteParams)
	// Get an investor by ID (public)
	// (GET /investors/{id})
	GetInvestor(c *gin.Context, id openapi_types.UUID)
	// Update the authenticated user's investor profile
	// (PUT /investors/{id})
	UpdateInvestor(c *gin.Context, id openapi_types.UUID)
	// Upload a logo image for the investor
	// (POST /investors/{id}/logo)
	UploadInvestorLogo(c *gin.Context, id openapi_types.UUID)
	// List all startup accounts (public)
	// (GET /startups)
	ListStartups(c *gin.Context)
	// Create a new startup account
	// (POST /startups)
	CreateStartup(c *gin.Context)
	// Check whether a website URL is already registered by a startup
	// (GET /startups/check-website)
	CheckStartupWebsite(c *gin.Context, params CheckStartupWebsiteParams)
	// Get a startup by ID (public)
	// (GET /startups/{id})
	GetStartup(c *gin.Context, id openapi_types.UUID)
	// Update the authenticated user's startup profile
	// (PUT /startups/{id})
	UpdateStartup(c *gin.Context, id openapi_types.UUID)
	// Upload or replace the banner image for the startup
	// (POST /startups/{id}/banner)
	UploadStartupBanner(c *gin.Context, id openapi_types.UUID)
	// Remove favorite from a startup for the authenticated user
	// (DELETE /startups/{id}/bookmark)
	UnfavoriteStartup(c *gin.Context, id openapi_types.UUID)
	// Favorite a startup for the authenticated user
	// (POST /startups/{id}/bookmark)
	FavoriteStartup(c *gin.Context, id openapi_types.UUID)
	// Boost a startup (irreversible, expires after 7 days)
	// (POST /startups/{id}/boost)
	BoostStartup(c *gin.Context, id openapi_types.UUID)
	// Upload a logo image for the startup
	// (POST /startups/{id}/logo)
	UploadStartupLogo(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// Verify operation middleware
func (siw *ServerInterfaceWrapper) Verify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Verify(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// ListInvestors operation middleware
func (siw *ServerInterfaceWrapper) ListInvestors(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInvestors(c)
}

// CreateInvestor operation middleware
func (siw *ServerInterfaceWrapper) CreateInvestor(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateInvestor(c)
}

// CheckInvestorWebsite operation middleware
func (siw *ServerInterfaceWrapper) CheckInvestorWebsite(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckInvestorWebsiteParams

	// ------------- Required query parameter "url" -------------

	if paramValue := c.Query("url"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument url is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "url", c.Request.URL.Query(), &params.Url)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter url: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckInvestorWebsite(c, params)
}

// GetInvestor operation middleware
func (siw *ServerInterfaceWrapper) GetInvestor(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInvestor(c, id)
}

// UpdateInvestor operation middleware
func (siw *ServerInterfaceWrapper) UpdateInvestor(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateInvestor(c, id)
}

// UploadInvestorLogo operation middleware
func (siw *ServerInterfaceWrapper) UploadInvestorLogo(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadInvestorLogo(c, id)
}

// ListStartups operation middleware
func (siw *ServerInterfaceWrapper) ListStartups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListStartups(c)
}

// CreateStartup operation middleware
func (siw *ServerInterfaceWrapper) CreateStartup(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStartup(c)
}

// CheckStartupWebsite operation middleware
func (siw *ServerInterfaceWrapper) CheckStartupWebsite(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckStartupWebsiteParams

	// ------------- Required query parameter "url" -------------

	if paramValue := c.Query("url"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument url is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "url", c.Request.URL.Query(), &params.Url)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter url: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckStartupWebsite(c, params)
}

// GetStartup operation middleware
func (siw *ServerInterfaceWrapper) GetStartup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStartup(c, id)
}

// UpdateStartup operation middleware
func (siw *ServerInterfaceWrapper) UpdateStartup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStartup(c, id)
}

// UploadStartupBanner operation middleware
func (siw *ServerInterfaceWrapper) UploadStartupBanner(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadStartupBanner(c, id)
}

// UnfavoriteStartup operation middleware
func (siw *ServerInterfaceWrapper) UnfavoriteStartup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UnfavoriteStartup(c, id)
}

// FavoriteStartup operation middleware
func (siw *ServerInterfaceWrapper) FavoriteStartup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FavoriteStartup(c, id)
}

// BoostStartup operation middleware
func (siw *ServerInterfaceWrapper) BoostStartup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BoostStartup(c, id)
}

// UploadStartupLogo operation middleware
func (siw *ServerInterfaceWrapper) UploadStartupLogo(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadStartupLogo(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/auth/verify", wrapper.Verify)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/investors", wrapper.ListInvestors)
	router.POST(options.BaseURL+"/investors", wrapper.CreateInvestor)
	router.GET(options.BaseURL+"/investors/check-website", wrapper.CheckInvestorWebsite)
	router.GET(options.BaseURL+"/investors/:id", wrapper.GetInvestor)
	router.PUT(options.BaseURL+"/investors/:id", wrapper.UpdateInvestor)
	router.POST(options.BaseURL+"/investors/:id/logo", wrapper.UploadInvestorLogo)
	router.GET(options.BaseURL+"/startups", wrapper.ListStartups)
	router.POST(options.BaseURL+"/startups", wrapper.CreateStartup)
	router.GET(options.BaseURL+"/startups/check-website", wrapper.CheckStartupWebsite)
	router.GET(options.BaseURL+"/startups/:id", wrapper.GetStartup)
	router.PUT(options.BaseURL+"/startups/:id", wrapper.UpdateStartup)
	router.POST(options.BaseURL+"/startups/:id/banner", wrapper.UploadStartupBanner)
	router.DELETE(options.BaseURL+"/startups/:id/bookmark", wrapper.UnfavoriteStartup)
	router.POST(options.BaseURL+"/startups/:id/bookmark", wrapper.FavoriteStartup)
	router.POST(options.BaseURL+"/startups/:id/boost", wrapper.BoostStartup)
	router.POST(options.BaseURL+"/startups/:id/logo", wrapper.UploadStartupLogo)
}
